package com.sdr.popup.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.popup.model.Popup;
import com.sdr.popup.service.PopupLocalServiceUtil;

/**
 * The extended model base implementation for the Popup service. Represents a row in the &quot;sdr_popup_Popup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PopupImpl}.
 * </p>
 *
 * @author goopsw
 * @see PopupImpl
 * @see com.sdr.popup.model.Popup
 * @generated
 */
public abstract class PopupBaseImpl extends PopupModelImpl implements Popup {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a popup model instance should use the {@link Popup} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PopupLocalServiceUtil.addPopup(this);
        } else {
            PopupLocalServiceUtil.updatePopup(this);
        }
    }
}
