package com.sdr.metadata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.metadata.model.ApiKey;
import com.sdr.metadata.service.ApiKeyLocalServiceUtil;

/**
 * The extended model base implementation for the ApiKey service. Represents a row in the &quot;sdr_ApiKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApiKeyImpl}.
 * </p>
 *
 * @author jaesung
 * @see ApiKeyImpl
 * @see com.sdr.metadata.model.ApiKey
 * @generated
 */
public abstract class ApiKeyBaseImpl extends ApiKeyModelImpl implements ApiKey {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a api key model instance should use the {@link ApiKey} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ApiKeyLocalServiceUtil.addApiKey(this);
        } else {
            ApiKeyLocalServiceUtil.updateApiKey(this);
        }
    }
}
