package com.sdr.metadata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.metadata.model.Collection_AllowedUser;
import com.sdr.metadata.service.Collection_AllowedUserLocalServiceUtil;

/**
 * The extended model base implementation for the Collection_AllowedUser service. Represents a row in the &quot;sdr_Collection_AllowedUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Collection_AllowedUserImpl}.
 * </p>
 *
 * @author jaesung
 * @see Collection_AllowedUserImpl
 * @see com.sdr.metadata.model.Collection_AllowedUser
 * @generated
 */
public abstract class Collection_AllowedUserBaseImpl
    extends Collection_AllowedUserModelImpl implements Collection_AllowedUser {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a collection_ allowed user model instance should use the {@link Collection_AllowedUser} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Collection_AllowedUserLocalServiceUtil.addCollection_AllowedUser(this);
        } else {
            Collection_AllowedUserLocalServiceUtil.updateCollection_AllowedUser(this);
        }
    }
}
