package com.sdr.metadata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.metadata.model.DataTypeSchema;
import com.sdr.metadata.service.DataTypeSchemaLocalServiceUtil;

/**
 * The extended model base implementation for the DataTypeSchema service. Represents a row in the &quot;sdr_DataTypeSchema&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataTypeSchemaImpl}.
 * </p>
 *
 * @author jaesung
 * @see DataTypeSchemaImpl
 * @see com.sdr.metadata.model.DataTypeSchema
 * @generated
 */
public abstract class DataTypeSchemaBaseImpl extends DataTypeSchemaModelImpl
    implements DataTypeSchema {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a data type schema model instance should use the {@link DataTypeSchema} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DataTypeSchemaLocalServiceUtil.addDataTypeSchema(this);
        } else {
            DataTypeSchemaLocalServiceUtil.updateDataTypeSchema(this);
        }
    }
}
