package com.sdr.metadata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.metadata.model.DataType;
import com.sdr.metadata.service.DataTypeLocalServiceUtil;

/**
 * The extended model base implementation for the DataType service. Represents a row in the &quot;sdr_DataType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataTypeImpl}.
 * </p>
 *
 * @author jaesung
 * @see DataTypeImpl
 * @see com.sdr.metadata.model.DataType
 * @generated
 */
public abstract class DataTypeBaseImpl extends DataTypeModelImpl
    implements DataType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a data type model instance should use the {@link DataType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DataTypeLocalServiceUtil.addDataType(this);
        } else {
            DataTypeLocalServiceUtil.updateDataType(this);
        }
    }
}
