package com.sdr.metadata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.metadata.model.IceBreakerVcToken;
import com.sdr.metadata.service.IceBreakerVcTokenLocalServiceUtil;

/**
 * The extended model base implementation for the IceBreakerVcToken service. Represents a row in the &quot;sdr_IceBreakerVcToken&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IceBreakerVcTokenImpl}.
 * </p>
 *
 * @author jaesung
 * @see IceBreakerVcTokenImpl
 * @see com.sdr.metadata.model.IceBreakerVcToken
 * @generated
 */
public abstract class IceBreakerVcTokenBaseImpl
    extends IceBreakerVcTokenModelImpl implements IceBreakerVcToken {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ice breaker vc token model instance should use the {@link IceBreakerVcToken} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IceBreakerVcTokenLocalServiceUtil.addIceBreakerVcToken(this);
        } else {
            IceBreakerVcTokenLocalServiceUtil.updateIceBreakerVcToken(this);
        }
    }
}
