package com.sdr.metadata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.metadata.model.PpLogic;
import com.sdr.metadata.service.PpLogicLocalServiceUtil;

/**
 * The extended model base implementation for the PpLogic service. Represents a row in the &quot;sdr_PpLogic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PpLogicImpl}.
 * </p>
 *
 * @author jaesung
 * @see PpLogicImpl
 * @see com.sdr.metadata.model.PpLogic
 * @generated
 */
public abstract class PpLogicBaseImpl extends PpLogicModelImpl
    implements PpLogic {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a pp logic model instance should use the {@link PpLogic} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PpLogicLocalServiceUtil.addPpLogic(this);
        } else {
            PpLogicLocalServiceUtil.updatePpLogic(this);
        }
    }
}
