package com.sdr.bbs.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.bbs.model.BbsPost;
import com.sdr.bbs.service.BbsPostLocalServiceUtil;

/**
 * The extended model base implementation for the BbsPost service. Represents a row in the &quot;sdr_bbs_BbsPost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BbsPostImpl}.
 * </p>
 *
 * @author goopsw
 * @see BbsPostImpl
 * @see com.sdr.bbs.model.BbsPost
 * @generated
 */
public abstract class BbsPostBaseImpl extends BbsPostModelImpl
    implements BbsPost {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bbs post model instance should use the {@link BbsPost} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BbsPostLocalServiceUtil.addBbsPost(this);
        } else {
            BbsPostLocalServiceUtil.updateBbsPost(this);
        }
    }
}
