package com.sdr.guide.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.guide.model.Guide;
import com.sdr.guide.service.GuideLocalServiceUtil;

/**
 * The extended model base implementation for the Guide service. Represents a row in the &quot;test_Guide&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GuideImpl}.
 * </p>
 *
 * @author heesangbb
 * @see GuideImpl
 * @see com.sdr.guide.model.Guide
 * @generated
 */
public abstract class GuideBaseImpl extends GuideModelImpl implements Guide {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a guide model instance should use the {@link Guide} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            GuideLocalServiceUtil.addGuide(this);
        } else {
            GuideLocalServiceUtil.updateGuide(this);
        }
    }
}
