package com.sdr.metadata.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Collection service. Represents a row in the &quot;sdr_Collection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sdr.metadata.model.impl.CollectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sdr.metadata.model.impl.CollectionImpl}.
 * </p>
 *
 * @author jaesung
 * @see Collection
 * @see com.sdr.metadata.model.impl.CollectionImpl
 * @see com.sdr.metadata.model.impl.CollectionModelImpl
 * @generated
 */
public interface CollectionModel extends BaseModel<Collection> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a collection model instance should use the {@link Collection} interface instead.
     */

    /**
     * Returns the primary key of this collection.
     *
     * @return the primary key of this collection
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this collection.
     *
     * @param primaryKey the primary key of this collection
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the collection ID of this collection.
     *
     * @return the collection ID of this collection
     */
    public long getCollectionId();

    /**
     * Sets the collection ID of this collection.
     *
     * @param collectionId the collection ID of this collection
     */
    public void setCollectionId(long collectionId);

    /**
     * Returns the title of this collection.
     *
     * @return the title of this collection
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this collection.
     *
     * @param title the title of this collection
     */
    public void setTitle(String title);

    /**
     * Returns the user ID of this collection.
     *
     * @return the user ID of this collection
     */
    public long getUserId();

    /**
     * Sets the user ID of this collection.
     *
     * @param userId the user ID of this collection
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this collection.
     *
     * @return the user uuid of this collection
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this collection.
     *
     * @param userUuid the user uuid of this collection
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this collection.
     *
     * @return the create date of this collection
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this collection.
     *
     * @param createDate the create date of this collection
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the description of this collection.
     *
     * @return the description of this collection
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this collection.
     *
     * @param description the description of this collection
     */
    public void setDescription(String description);

    /**
     * Returns the usage right of this collection.
     *
     * @return the usage right of this collection
     */
    @AutoEscape
    public String getUsageRight();

    /**
     * Sets the usage right of this collection.
     *
     * @param usageRight the usage right of this collection
     */
    public void setUsageRight(String usageRight);

    /**
     * Returns the doi of this collection.
     *
     * @return the doi of this collection
     */
    @AutoEscape
    public String getDoi();

    /**
     * Sets the doi of this collection.
     *
     * @param doi the doi of this collection
     */
    public void setDoi(String doi);

    /**
     * Returns the access policy of this collection.
     *
     * @return the access policy of this collection
     */
    public int getAccessPolicy();

    /**
     * Sets the access policy of this collection.
     *
     * @param accessPolicy the access policy of this collection
     */
    public void setAccessPolicy(int accessPolicy);

    /**
     * Returns the group ID of this collection.
     *
     * @return the group ID of this collection
     */
    public long getGroupId();

    /**
     * Sets the group ID of this collection.
     *
     * @param groupId the group ID of this collection
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this collection.
     *
     * @return the company ID of this collection
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this collection.
     *
     * @param companyId the company ID of this collection
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the skip curate of this collection.
     *
     * @return the skip curate of this collection
     */
    public boolean getSkipCurate();

    /**
     * Returns <code>true</code> if this collection is skip curate.
     *
     * @return <code>true</code> if this collection is skip curate; <code>false</code> otherwise
     */
    public boolean isSkipCurate();

    /**
     * Sets whether this collection is skip curate.
     *
     * @param skipCurate the skip curate of this collection
     */
    public void setSkipCurate(boolean skipCurate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.sdr.metadata.model.Collection collection);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.sdr.metadata.model.Collection> toCacheModel();

    @Override
    public com.sdr.metadata.model.Collection toEscapedModel();

    @Override
    public com.sdr.metadata.model.Collection toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
