package com.sdr.metadata.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DataTypeSchema service. Represents a row in the &quot;sdr_DataTypeSchema&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sdr.metadata.model.impl.DataTypeSchemaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sdr.metadata.model.impl.DataTypeSchemaImpl}.
 * </p>
 *
 * @author jaesung
 * @see DataTypeSchema
 * @see com.sdr.metadata.model.impl.DataTypeSchemaImpl
 * @see com.sdr.metadata.model.impl.DataTypeSchemaModelImpl
 * @generated
 */
public interface DataTypeSchemaModel extends BaseModel<DataTypeSchema> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a data type schema model instance should use the {@link DataTypeSchema} interface instead.
     */

    /**
     * Returns the primary key of this data type schema.
     *
     * @return the primary key of this data type schema
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this data type schema.
     *
     * @param primaryKey the primary key of this data type schema
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the data type schema ID of this data type schema.
     *
     * @return the data type schema ID of this data type schema
     */
    public long getDataTypeSchemaId();

    /**
     * Sets the data type schema ID of this data type schema.
     *
     * @param dataTypeSchemaId the data type schema ID of this data type schema
     */
    public void setDataTypeSchemaId(long dataTypeSchemaId);

    /**
     * Returns the title of this data type schema.
     *
     * @return the title of this data type schema
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this data type schema.
     *
     * @param title the title of this data type schema
     */
    public void setTitle(String title);

    /**
     * Returns the reference of this data type schema.
     *
     * @return the reference of this data type schema
     */
    @AutoEscape
    public String getReference();

    /**
     * Sets the reference of this data type schema.
     *
     * @param reference the reference of this data type schema
     */
    public void setReference(String reference);

    /**
     * Returns the variable type of this data type schema.
     *
     * @return the variable type of this data type schema
     */
    @AutoEscape
    public String getVariableType();

    /**
     * Sets the variable type of this data type schema.
     *
     * @param variableType the variable type of this data type schema
     */
    public void setVariableType(String variableType);

    /**
     * Returns the variable unit of this data type schema.
     *
     * @return the variable unit of this data type schema
     */
    @AutoEscape
    public String getVariableUnit();

    /**
     * Sets the variable unit of this data type schema.
     *
     * @param variableUnit the variable unit of this data type schema
     */
    public void setVariableUnit(String variableUnit);

    /**
     * Returns the essential of this data type schema.
     *
     * @return the essential of this data type schema
     */
    public Boolean getEssential();

    /**
     * Sets the essential of this data type schema.
     *
     * @param essential the essential of this data type schema
     */
    public void setEssential(Boolean essential);

    /**
     * Returns the minimum of this data type schema.
     *
     * @return the minimum of this data type schema
     */
    public Double getMinimum();

    /**
     * Sets the minimum of this data type schema.
     *
     * @param minimum the minimum of this data type schema
     */
    public void setMinimum(Double minimum);

    /**
     * Returns the maximum of this data type schema.
     *
     * @return the maximum of this data type schema
     */
    public Double getMaximum();

    /**
     * Sets the maximum of this data type schema.
     *
     * @param maximum the maximum of this data type schema
     */
    public void setMaximum(Double maximum);

    /**
     * Returns the enums of this data type schema.
     *
     * @return the enums of this data type schema
     */
    @AutoEscape
    public String getEnums();

    /**
     * Sets the enums of this data type schema.
     *
     * @param enums the enums of this data type schema
     */
    public void setEnums(String enums);

    /**
     * Returns the pattern of this data type schema.
     *
     * @return the pattern of this data type schema
     */
    @AutoEscape
    public String getPattern();

    /**
     * Sets the pattern of this data type schema.
     *
     * @param pattern the pattern of this data type schema
     */
    public void setPattern(String pattern);

    /**
     * Returns the description of this data type schema.
     *
     * @return the description of this data type schema
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this data type schema.
     *
     * @param description the description of this data type schema
     */
    public void setDescription(String description);

    /**
     * Returns the user ID of this data type schema.
     *
     * @return the user ID of this data type schema
     */
    public long getUserId();

    /**
     * Sets the user ID of this data type schema.
     *
     * @param userId the user ID of this data type schema
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this data type schema.
     *
     * @return the user uuid of this data type schema
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this data type schema.
     *
     * @param userUuid the user uuid of this data type schema
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the group ID of this data type schema.
     *
     * @return the group ID of this data type schema
     */
    public long getGroupId();

    /**
     * Sets the group ID of this data type schema.
     *
     * @param groupId the group ID of this data type schema
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this data type schema.
     *
     * @return the company ID of this data type schema
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this data type schema.
     *
     * @param companyId the company ID of this data type schema
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the create user ID of this data type schema.
     *
     * @return the create user ID of this data type schema
     */
    public long getCreateUserId();

    /**
     * Sets the create user ID of this data type schema.
     *
     * @param createUserId the create user ID of this data type schema
     */
    public void setCreateUserId(long createUserId);

    /**
     * Returns the create user uuid of this data type schema.
     *
     * @return the create user uuid of this data type schema
     * @throws SystemException if a system exception occurred
     */
    public String getCreateUserUuid() throws SystemException;

    /**
     * Sets the create user uuid of this data type schema.
     *
     * @param createUserUuid the create user uuid of this data type schema
     */
    public void setCreateUserUuid(String createUserUuid);

    /**
     * Returns the create date of this data type schema.
     *
     * @return the create date of this data type schema
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this data type schema.
     *
     * @param createDate the create date of this data type schema
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this data type schema.
     *
     * @return the modified date of this data type schema
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this data type schema.
     *
     * @param modifiedDate the modified date of this data type schema
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the status of this data type schema.
     *
     * @return the status of this data type schema
     */
    public int getStatus();

    /**
     * Sets the status of this data type schema.
     *
     * @param status the status of this data type schema
     */
    public void setStatus(int status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.sdr.metadata.model.DataTypeSchema dataTypeSchema);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.sdr.metadata.model.DataTypeSchema> toCacheModel();

    @Override
    public com.sdr.metadata.model.DataTypeSchema toEscapedModel();

    @Override
    public com.sdr.metadata.model.DataTypeSchema toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
