package com.sdr.metadata.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DataView service. Represents a row in the &quot;sdr_DataView&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sdr.metadata.model.impl.DataViewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sdr.metadata.model.impl.DataViewImpl}.
 * </p>
 *
 * @author jaesung
 * @see DataView
 * @see com.sdr.metadata.model.impl.DataViewImpl
 * @see com.sdr.metadata.model.impl.DataViewModelImpl
 * @generated
 */
public interface DataViewModel extends BaseModel<DataView> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a data view model instance should use the {@link DataView} interface instead.
     */

    /**
     * Returns the primary key of this data view.
     *
     * @return the primary key of this data view
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this data view.
     *
     * @param primaryKey the primary key of this data view
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the data view ID of this data view.
     *
     * @return the data view ID of this data view
     */
    public long getDataViewId();

    /**
     * Sets the data view ID of this data view.
     *
     * @param dataViewId the data view ID of this data view
     */
    public void setDataViewId(long dataViewId);

    /**
     * Returns the title of this data view.
     *
     * @return the title of this data view
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this data view.
     *
     * @param title the title of this data view
     */
    public void setTitle(String title);

    /**
     * Returns the data type ID of this data view.
     *
     * @return the data type ID of this data view
     */
    public long getDataTypeId();

    /**
     * Sets the data type ID of this data view.
     *
     * @param dataTypeId the data type ID of this data view
     */
    public void setDataTypeId(long dataTypeId);

    /**
     * Returns the html of this data view.
     *
     * @return the html of this data view
     */
    @AutoEscape
    public String getHtml();

    /**
     * Sets the html of this data view.
     *
     * @param html the html of this data view
     */
    public void setHtml(String html);

    /**
     * Returns the description of this data view.
     *
     * @return the description of this data view
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this data view.
     *
     * @param description the description of this data view
     */
    public void setDescription(String description);

    /**
     * Returns the group ID of this data view.
     *
     * @return the group ID of this data view
     */
    public long getGroupId();

    /**
     * Sets the group ID of this data view.
     *
     * @param groupId the group ID of this data view
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this data view.
     *
     * @return the company ID of this data view
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this data view.
     *
     * @param companyId the company ID of this data view
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this data view.
     *
     * @return the user ID of this data view
     */
    public long getUserId();

    /**
     * Sets the user ID of this data view.
     *
     * @param userId the user ID of this data view
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this data view.
     *
     * @return the user uuid of this data view
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this data view.
     *
     * @param userUuid the user uuid of this data view
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the status of this data view.
     *
     * @return the status of this data view
     */
    public int getStatus();

    /**
     * Sets the status of this data view.
     *
     * @param status the status of this data view
     */
    public void setStatus(int status);

    /**
     * Returns the order no of this data view.
     *
     * @return the order no of this data view
     */
    public int getOrderNo();

    /**
     * Sets the order no of this data view.
     *
     * @param orderNo the order no of this data view
     */
    public void setOrderNo(int orderNo);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.sdr.metadata.model.DataView dataView);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.sdr.metadata.model.DataView> toCacheModel();

    @Override
    public com.sdr.metadata.model.DataView toEscapedModel();

    @Override
    public com.sdr.metadata.model.DataView toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
